/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.intecap.minibanco.vista.paneles;

/**
 *
 * @author Nelcy
 */
public class PanelTipoCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelCliente
     */
    public PanelTipoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTipoCliente = new javax.swing.JLabel();
    separador = new javax.swing.JSeparator();
    pnTiposExistentes = new javax.swing.JPanel();
    lblTiposExistentes = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tbTiposExistentes = new javax.swing.JTable();
    pnIngresarTipos = new javax.swing.JPanel();
    lblIngresarTipos = new javax.swing.JLabel();
    lblNombre = new javax.swing.JLabel();
    lblEstado = new javax.swing.JLabel();
    txtfNombre = new javax.swing.JTextField();
    btnLimpiar = new javax.swing.JButton();
    btnRegistrarActualizar = new javax.swing.JButton();
    cbxEstado = new javax.swing.JCheckBox();

    lblTipoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblTipoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTipoCliente.setText("Tipo Cliente");

    pnTiposExistentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    lblTiposExistentes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lblTiposExistentes.setText("Tipos Existentes");

    tbTiposExistentes.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "id_tipo_cliente", "nombre", "estado"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane2.setViewportView(tbTiposExistentes);

    javax.swing.GroupLayout pnTiposExistentesLayout = new javax.swing.GroupLayout(pnTiposExistentes);
    pnTiposExistentes.setLayout(pnTiposExistentesLayout);
    pnTiposExistentesLayout.setHorizontalGroup(
      pnTiposExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnTiposExistentesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTiposExistentes)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTiposExistentesLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
    );
    pnTiposExistentesLayout.setVerticalGroup(
      pnTiposExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTiposExistentesLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblTiposExistentes)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
    );

    pnIngresarTipos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    lblIngresarTipos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lblIngresarTipos.setText("Ingresar Tipos");

    lblNombre.setText("Nombre");

    lblEstado.setText("Estado");

    btnLimpiar.setText("Limpiar");

    btnRegistrarActualizar.setText("Registrar / Actualizar");
    btnRegistrarActualizar.setToolTipText("");

    cbxEstado.setSelected(true);
    cbxEstado.setText("Activo");

    javax.swing.GroupLayout pnIngresarTiposLayout = new javax.swing.GroupLayout(pnIngresarTipos);
    pnIngresarTipos.setLayout(pnIngresarTiposLayout);
    pnIngresarTiposLayout.setHorizontalGroup(
      pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnIngresarTiposLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblIngresarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIngresarTiposLayout.createSequentialGroup()
            .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIngresarTiposLayout.createSequentialGroup()
                .addComponent(lblNombre)
                .addGap(33, 33, 33))
              .addGroup(pnIngresarTiposLayout.createSequentialGroup()
                .addComponent(lblEstado)
                .addGap(37, 37, 37)))
            .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cbxEstado)
              .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIngresarTiposLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnLimpiar)
        .addGap(17, 17, 17)
        .addComponent(btnRegistrarActualizar)
        .addContainerGap())
    );
    pnIngresarTiposLayout.setVerticalGroup(
      pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnIngresarTiposLayout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(lblIngresarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblNombre))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbxEstado)
          .addComponent(lblEstado))
        .addGap(15, 15, 15)
        .addGroup(pnIngresarTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLimpiar)
          .addComponent(btnRegistrarActualizar))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(pnIngresarTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(pnTiposExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(separador)
            .addContainerGap())))
      .addGroup(layout.createSequentialGroup()
        .addGap(225, 225, 225)
        .addComponent(lblTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 239, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(lblTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(pnIngresarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(pnTiposExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JButton btnRegistrarActualizar;
  private javax.swing.JCheckBox cbxEstado;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lblEstado;
  private javax.swing.JLabel lblIngresarTipos;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblTipoCliente;
  private javax.swing.JLabel lblTiposExistentes;
  private javax.swing.JPanel pnIngresarTipos;
  private javax.swing.JPanel pnTiposExistentes;
  private javax.swing.JSeparator separador;
  private javax.swing.JTable tbTiposExistentes;
  private javax.swing.JTextField txtfNombre;
  // End of variables declaration//GEN-END:variables
}
