/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.intecap.minibanco.vista;

import co.edu.intecap.minibanco.vista.paneles.PanelCliente;
import co.edu.intecap.minibanco.vista.paneles.VentanaCliente;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Capacitaciones_pc18
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initListeners();
        this.setTitle("Aplicación MiniBanco");
        this.setLocationRelativeTo(null);
        this.setMinimumSize(new Dimension(500, 430));
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        mnuAdministracion.setVisible(false);
        mnuTransacciones.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        miAdminCliente = new javax.swing.JMenuItem();
        miAdminTipoProducto = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuTransacciones = new javax.swing.JMenu();
        mnuOpciones = new javax.swing.JMenu();
        miIngresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout dpContenedorLayout = new javax.swing.GroupLayout(dpContenedor);
        dpContenedor.setLayout(dpContenedorLayout);
        dpContenedorLayout.setHorizontalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        dpContenedorLayout.setVerticalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        getContentPane().add(dpContenedor);

        mnuAdministracion.setText("Administración");

        miAdminCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        miAdminCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/intecap/minibanco/vista/resources/iconos/account-edit.png"))); // NOI18N
        miAdminCliente.setText("Administrar Clientes");
        mnuAdministracion.add(miAdminCliente);

        miAdminTipoProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        miAdminTipoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/intecap/minibanco/vista/resources/iconos/table-edit.png"))); // NOI18N
        miAdminTipoProducto.setText("Administrar Tipo Producto");
        mnuAdministracion.add(miAdminTipoProducto);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/intecap/minibanco/vista/resources/iconos/cliente-producto.png"))); // NOI18N
        jMenuItem3.setText("Administrar Cliente Producto");
        mnuAdministracion.add(jMenuItem3);

        jMenuBar1.add(mnuAdministracion);

        mnuTransacciones.setText("Transacciones");
        jMenuBar1.add(mnuTransacciones);

        mnuOpciones.setText("Opciones");

        miIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        miIngresar.setText("Ingresar");
        miIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIngresarActionPerformed(evt);
            }
        });
        mnuOpciones.add(miIngresar);

        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIngresarActionPerformed
        new VentanaLogin(this, this, true).setVisible(true);
    }//GEN-LAST:event_miIngresarActionPerformed

    public void habilitarMenu() {
        mnuAdministracion.setVisible(true);
        mnuTransacciones.setVisible(true);
        miIngresar.setVisible(false);
    }

    private void initListeners() {
        ActionListener eventoClickMenu = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                JInternalFrame subVentana = null;
                JMenuItem menuEvento = (JMenuItem) ae.getSource();
                subVentana = asignarPanel(menuEvento);
                subVentana.setVisible(true);
                dpContenedor.add(subVentana);
                System.out.println("Dimensiones: "+subVentana.getBounds());
            }
        };

        miAdminCliente.addActionListener(eventoClickMenu);
        miAdminTipoProducto.addActionListener(eventoClickMenu);
    }

    private JInternalFrame asignarPanel(JMenuItem menuEvento) {
        JInternalFrame panel = null;
        if (menuEvento.equals(miAdminCliente)) {
            panel = new VentanaCliente();
        }
        return panel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpContenedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem miAdminCliente;
    private javax.swing.JMenuItem miAdminTipoProducto;
    private javax.swing.JMenuItem miIngresar;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuTransacciones;
    // End of variables declaration//GEN-END:variables
}
